[tool.poetry]
name = "undis"
version = "0.1.0"
description = ""
authors = ["ToroidalFox <93528864+ToroidalFox@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pdoc = "^14.1.0"
toml = "^0.10.2"
typing-extensions = "^4.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
